# Generated by Django 3.0.3 on 2020-08-26 21:11

from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('dean', models.CharField(max_length=45, unique=True)),
                ('detail', models.TextField()),
                ('detail_html', models.TextField(editable=False)),
                ('faculty_slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=faculty.models.get_image_filename, verbose_name='faculty_image')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_images', to='faculty.Faculty')),
            ],
        ),
    ]
