# Generated by Django 3.0.3 on 2020-08-26 21:11

import departments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('chairman', models.CharField(max_length=45, unique=True)),
                ('detail', models.TextField()),
                ('detail_html', models.TextField(editable=False)),
                ('department_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('acronyms', models.CharField(max_length=10)),
                ('established_date', models.DateTimeField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculty.Faculty', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=departments.models.get_image_filename, verbose_name='department_image')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_images', to='departments.Department')),
            ],
        ),
    ]
