# Generated by Django 3.0.3 on 2020-08-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='teachers/profile_pics')),
                ('Teacher_ID', models.CharField(max_length=20, unique=True)),
                ('portfolio_site', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('academic_rank', models.CharField(max_length=45)),
                ('teacher_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='departments.Department', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Teacher_ID'],
                'unique_together': {('Teacher_ID', 'department')},
            },
        ),
    ]
