# Generated by Django 3.0.3 on 2020-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200827_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_rank',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant professor', 'Assistant professor'), ('Associate professor', 'Associate professor'), ('Professor', 'Professor'), ('Professor emeritus', 'Professor emeritus')], max_length=100),
        ),
    ]
